### ISSUE TITLE
Support for video comments

### ISSUE THREAD

**Issue by yashjawale** [rtCamp/godam#583]
Comments functionality is required for YouTube theme & later on could be used for Instagram theme

It would be better to add this support at the plugin level as the feature is quite common & multiple themes can benefit from this in the future

This functionality should still work without explicit theme support for GoDAM users who use GoDAM gallery / video blocks

## Methodology
- Video comments will be stored in CMM instead of WordPress DB
- REST API will be available for the same
- Once the API becomes available, we need to make default WordPress's comment system work with CMM comments implementation, this way `comments_tempate()` & default comments block should work without much modifications
- Whether the comments support nesting will be dictated by the implemented API
- We can intercept WordPress comment requests & route then through the REST API to store them there instead
- In plugin, comments can be linked to godam video CPT

## Notes
- Can use `pre_comment_approved` / `comment_post` filter to save comment to REST API instead of saving to database
- Need to override results returned from `get_comments()` function so that comments template & comments block work as expected
- `comments_clauses` can be used to disable DB query for fetching comments & `comments_array` / `the_comments` to create `WP_Comment` instances according to results from REST API
- Intercept comment form submissions with `pre_comment_on_post` to store comment data into CMM

**Comment by nayemDevs** [comment]
@OpuRockey, please post the latest update on the completion of requested adjustments.

**Comment by OpuRockey** [comment]
Based on the requested adjustment what we have done.

1. Enabled register/login for likes, comments engagements.
2. Server time is used for comments timestamp.
3. For non-logged in user, we are showing them a register / login link box on the comment modal. By clicking on the link, they will be redirected to the respected login page. By default it will redirect to wp-login.php page. But link can be modified via filter `( rtgodam-site-login-url,  rtgodam-site-registration-url )`.
4. As a secondary option, we have created an option for the no-logged in user. In that case, they will simply put their email address. System will remember that email for an hour. They can like & comment. We have disabled that feature for now.
5.  For likes and comments we have cached the data in WP.
6. On the comment box, timestamp button is added. User can now put specific time of the video to be played on the comment.

**Comment by nayemDevs** [comment]
@OpuRockey please post the update; we need to wrap up the code review and QA.

**Comment by OpuRockey** [comment]
Hello @kishan-gondaliya-7270, Can you please QA , Can you please QA this feature? You will find necessary information [here](https://github.com/rtCamp/godam/pull/903#issue-3317315175). Thanks.

**Comment by nayemDevs** [comment]
@OpuRockey please share your feedback - We are having so much delay to merge PR and QA.

**Comment by maharrshi** [comment]
### QA Testing Checklist

#### A. Engagement Bar (Single Video Block)
- [ ] Engagement bar is visible when engagement is enabled.
- [ ] Counts (likes, comments, views) display correctly .
- [ ] Like icon clickable: increments the like count; persists after page reload.
- [ ] Comment icon clickable: opens the comment modal.
- [ ] Views count reflects actual data from API/cache.
- [ ] Ensure the bar doesn’t appear if engagement toggled off in editor.
- [ ] Like/comment should not work for non-logged-in user; clicking shows prompt to log in.

#### B. Comment Modal Functionality
- [ ] Modal displays video, comments list, and comment input area.
- [ ] User can create new comment; comment appears immediately (and after reload).
- [ ] User can edit their own comment; changes persist.
- [ ] User can delete their own comment.
- [ ] Timestamp links in comments: clicking jumps video playback to proper timestamp.
- [ ] Single level comment to work.
- [ ] Submit empty comment → prevent submission and show error like “parameter should not be empty”.
- [ ] Non-logged-in try to comment/edit/delete → block interaction and prompt login.

#### C. Likes Functionality
- [ ] Click like → like count increments, visual feedback (e.g., animation, highlight).
- [ ] Animation duration of 500ms was set.
- [ ] Unlike toggles like count correctly.
- [ ] Like status persists on reload via cache/API.
- [ ] Non-logged-in cannot like; verify correct blocking.

#### D. Views Display
- [ ] Single video block displays views count, accurate as per API.
- [ ] Confirm no layout break when views are long numbers or missing.

#### E. Access Control (Logged-in vs Non-logged-in Users)
- [ ] Logged-in users: can view counts and perform like/comment/edit/delete operations.
- [ ] Non-logged-in users: can view comments and no of likes
- [ ] Non-logged-in clicking action should evoke login prompt, not undefined behavior.
- [ ] API calls should respect auth state and not leak data.


#### G. Edge Cases & Robustness
- [ ] Timestamp parsing: invalid formats (e.g., “99:99”) handled gracefully; no crash.
- [ ] Submitting extremely long comment → truncation/scroll; UI remains intact.
- [ ] Special chars work as expected for the comment box.
- [ ] Modal open/close actions work repeatedly without memory leaks.
- [ ] Test on mobile viewport: UI responsiveness and comment modal usability.
- [ ] Multisite scenario: liking/commenting works across subsites correctly, permissions respected.
- [ ] Comments by Central user and comments by wordpress user should be shown properly without any issues.

**Comment by maharrshi** [comment]
Hi @OpuRockey , please check the above listed issues.

**Comment by OpuRockey** [comment]
> Views are not displayed for the videos, always the count is shown as 0 itself

We have used a local cache for this for performance. It will be updated in every hour.

**Comment by OpuRockey** [comment]
> 4: Entering "&" in a comment results in it being displayed as "& amp; "

This issue is related to CMM API end. If we fix it there, it will be fixed automatically in everywhere. 
Ref: https://app-godam.rt.gw/web/video/4brtpj9ks7

**Comment by OpuRockey** [comment]
> 4: Entering "&" in a comment results in it being displayed as "& amp; "

This is fixed. 
PR: https://github.com/rtCamp/godam/pull/1013
Branch: https://github.com/rtCamp/godam/tree/fix/like_comments_views_qa_issues

**Comment by OpuRockey** [comment]
> 6: With focus on the comment section, pressing on Enter key loads . There should be a warning message something like "Please enter a comment to submit" instead of a spinner appearing.

This is fixed.
PR: https://github.com/rtCamp/godam/pull/1013
Branch: https://github.com/rtCamp/godam/tree/fix/like_comments_views_qa_issues

**Comment by OpuRockey** [comment]
> For views count, caching hourly might cause confusion for users who see 0 even after watching. Can we reduce the cache interval (e.g. 5–10 mins) or show an immediate count update for better UX?

We can reduce the cache interval time to 5 - 10 mins but min 1 hour caching is an standard option. @nayemDevs , Please tell us what we should do here.

**Comment by OpuRockey** [comment]
> Enhancement: The design of the popup modal that comes for commenting should be matching with what we have on GoDAM central.For instance currently there is no emoji options available, nested comments look is different etc. We want to keep the design same.

We will add that feature after first release.

**Comment by OpuRockey** [comment]
Necessary changes are applied as per discussion.

CC: @subodhr258

**Comment by maharrshi** [comment]
Hi @OpuRockey please find the below issue: 
1: Views for the video is still shown as 0 , for [this post](https://manoj-single-site-qa.rt.gw/2025/09/02/tst-test/) I have played on several browsers with several users but still count is 0.

2: Registered user is shown in the wordpress user section, but the post where liking the video is present, again Register/Login is being shown instead of allowing the user to like or comment on the video.
Link to post : https://manoj-single-site-qa.rt.gw/2025/09/02/tst-test/
Visual Proof:

https://github.com/user-attachments/assets/26e5eaa1-dd8d-43ec-9b4a-7348909dfe8d

**Comment by maharrshi** [comment]
Hi @subodhr258 , please let me know when the first issue is fixed.

**Comment by maharrshi** [comment]
@OpuRockey , please add your notes for 2nd issue that we discussed yesterday over the call.

**Comment by OpuRockey** [comment]
How comments works in WP

1. After initial load, system will pull comments data from `godam_core.api.comment.get_wp_comments` for name (The name (ID) of the Transcoder Job.)
2. Then system build nested comment structure.
3. Base on the logged in data ( wp user email ), it will check ( in loop ) if comment author email is matched with current logged in user email OR not.
4. If it is matched, it will give the access to edit OR delete.
5. When doing edit OR delete a comment, system will pull the logged in user data ( user email as `comment_email `) and send it to the API `godam_core.api.comment.wp_update_comment` and `godam_core.api.comment.delete_comment` with other params like `reference_name ( The name (ID) of the Transcoder Job. )`.

**Comment by kishan-gondaliya-7270** [comment]
Released with 1.4.0 
@OpuRockey I am closing old tickets, if you make any changes please create new task for same
